apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-server
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: "4.26.3"
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    image:
      repository: itzg/minecraft-server
      tag: latest
    minecraftServer:
      eula: true
      serviceType: LoadBalancer
      onlineMode: false
      rcon:
        enabled: true
        withGeneratedPassword: true
    workloadAsStatefulSet: true
    strategyType: RollingUpdate
    version: 1.21.5
    livenessProbe:
      command: ["true"]
    readinessProbe:
      command: ["true"]
    persistence:
      dataDir:
        enabled: true
        Size: 5Gi
